mamitha git

diff --git a/welcome-react/Jenkinsfile b/welcome-react/Jenkinsfile
--- a/welcome-react/Jenkinsfile
+++ b/welcome-react/Jenkinsfile
@@ -1,35 +1,50 @@
 pipeline {
     agent any
 
-    tools {
-        nodejs 'NodeJS-22'
+    environment {
+        IMAGE_NAME = "react-app"
+        CONTAINER_NAME = "blissful_pascal"
     }
 
     stages {
 
-        stage('Install Dependencies') {
+        stage('Clone Code') {
             steps {
-                dir('welcome-react') {
-                    bat 'npm install'
-                }
+                git branch: 'main',
+                    url: 'https://github.com/JA10-git/NSDC.git'
             }
         }
 
-        stage('Build React App') {
+        stage('Build Docker Image') {
             steps {
-                dir('welcome-react') {
-                    bat 'npm run build'
-                }
+                bat 'docker build -t %IMAGE_NAME% .'
+            }
+        }
+
+        stage('Stop Old Container') {
+            steps {
+                bat '''
+                docker stop %CONTAINER_NAME% || exit 0
+                docker rm %CONTAINER_NAME% || exit 0
+                '''
+            }
+        }
+
+        stage('Run Docker Container') {
+            steps {
+                bat '''
+                docker run -d -p 5173:5173 --name %CONTAINER_NAME% %IMAGE_NAME%
+                '''
             }
         }
     }
 
     post {
         success {
-            echo 'React build successful 🎉'
+            echo 'React app deployed using Docker successfully 🎉'
         }
         failure {
-            echo 'Build failed ❌'
+            echo 'Deployment failed ❌'
         }
     }
 }
